name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for tests
      run: dotnet restore TimestampMicroservice/TimeStampMicroservice.Tests/TimeStampMicroservice.Tests.csproj
      
    - name: Test
      run: dotnet test TimestampMicroservice/TimeStampMicroservice.Tests/TimeStampMicroservice.Tests.csproj --no-restore --verbosity normal
